export async function initCoreModules(ctx) {
  const {
    state,
    refs,
    runtime,
    taskActions,
    deps,
  } = ctx;

  const {
    renderTaskView,
    deleteTaskFn,
    saveModalHandler,
  } = taskActions;

  const {
    AccurateTimer,
    HOLIDAY_PRESETS,
    DEFAULT_FLIGHT_SETTINGS,
    initToast,
    showToast,
    initFlightOrchestrator,
    setCustomImageData,
    setCustomAudioData,
    setToastFn,
    initCountdownTimer,
    updateCountdownTaskUI,
    initAlarmChecker,
    initEmergency,
    WebviewWindow,
    initHeroSection,
    initFlightPreview,
    initFlightListeners,
    queueFlight,
    createMiniWindow,
    initTauriListeners,
    listen,
    stopLoopSoundLocal,
    stopLoopSound,
    clearAllSequences,
    clearFlightQueue,
    clearFlightStreak,
    pauseCountdown,
    stopCountdown,
    startCountdown,
    invoke,
    createCountdownTask,
    triggerEmergencyLanding,
    saveTasks,
    getCleanTasks,
    autoCheckForUpdate,
    getCurrentWebviewWindow,
    initMediaUpload,
    buildCustomAudioObjectUrl,
    syncAudioObjectUrlTo,
    updateSoundMeta,
    setCustomAudioObjectUrl,
    stopPreviewAudio,
    resetAudioPreview,
    revokeCustomAudioObjectUrl,
    unlockAudioIfNeeded,
    validateCustomAudioPreview,
    initWindowEvents,
    set,
    initTaskFilter,
    initSettingsPanel,
    setMuted,
    syncMuteToTray,
    persistSetting, syncThemeButtons, applyTheme,
    enableAutostart,
    disableAutostart,
    closeMiniWindow,
    positionMiniWindow,
    getMiniPositions,
    updateMiniPosGridActive,
    exportTasksAsJson,
    readBackupFromFile,
    hydrateTasks,
    setNextId,
    checkForUpdate,
    openFeedbackPage,
    openReleasePage,
    getCurrentVersion,
    previewCustomSound,
    previewFlight,
    resetFlightSettings,
    persistFlightSettings,
    initModalEvents,
    openNewModal,
    closeModal,
    openEditModal,
    selectColor,
    createAlarmTask,
  } = deps;

  initToast(refs.toastEl);

  initFlightOrchestrator({
    soundSelect: refs.soundSelect,
    soundModeSelect: refs.soundModeSelect,
    useSoundCheckbox: refs.useSoundCheckbox,
    speedSelect: refs.speedSelect,
    heightSelect: refs.heightSelect,
    effectSelect: refs.effectSelect,
    planeSelect: refs.planeSelect,
    planeSizeSelect: refs.planeSizeSelect,
    particleSelect: refs.particleSelect,
    bubbleSelect: refs.bubbleSelect,
    bubblePositionSelect: refs.bubblePositionSelect,
    bubbleSizeSelect: refs.bubbleSizeSelect,
    bubbleBgColor: refs.bubbleBgColor,
    bubbleFontColor: refs.bubbleFontColor,
    displaySelect: refs.displaySelect,
    useImageCheckbox: refs.useImageCheckbox,
  });
  setCustomImageData(state.customImageData);
  setCustomAudioData(state.customAudioData);
  setToastFn(showToast);

  initCountdownTimer({
    AccurateTimer,
    renderTaskView,
    saveTasks,
    getCleanTasks,
    getTasks: () => state.tasks,
    updateCountdownTaskUI,
    taskListEl: refs.taskListEl,
    holidayPresets: HOLIDAY_PRESETS,
    doTriggerFlight: deps.doTriggerFlight,
    updateMiniWindow: deps.updateMiniWindow,
    getAllUpcomingTasks: deps.getAllUpcomingTasks,
  });

  initAlarmChecker({
    getTasks: () => state.tasks,
    saveTasks,
    getCleanTasks: (tasks) => getCleanTasks(tasks),
    doTriggerFlight: deps.doTriggerFlight,
    showToast,
    renderTasks: renderTaskView,
    updateNextUpcoming: deps.updateNextUpcoming,
    updateMiniWindow: deps.updateMiniWindow,
    isInQuietHours: deps.isInQuietHours,
    getQuietHoursConfig: () => ({
      quietHoursToggle: refs.quietHoursToggle,
      quietStartHour: refs.quietStartHour,
      quietEndHour: refs.quietEndHour,
    }),
    normalizeRepeat: deps.normalizeRepeat,
    isAlarmDueToday: deps.isAlarmDueToday,
  });

  initEmergency({
    getModal: () => refs.modal,
    getSettingsModal: () => refs.settingsModal,
    stopLoopSoundLocal,
    stopFlightLoopSound: stopLoopSound,
    stopPreviewAudio,
    clearAllSequences,
    clearFlightQueue,
    clearFlightStreak: () => clearFlightStreak(),
    stopAllCountdowns: (tasks) => deps.stopAllCountdowns(tasks),
    getWebviewWindows: () => WebviewWindow.getAll(),
    showToast,
    emergencyBtn: refs.emergencyBtn,
    tasksRef: () => state.tasks,
    resetVideoWindowState: deps.resetVideoWindowState,
    resetPfNotifyState: deps.resetPfNotifyState,
    closePostFlightNotify: deps.closePostFlightNotify,
    setEmergencyLandingActive: deps.setEmergencyLandingActive,
    isEmergencyLandingActive: deps.isEmergencyLandingActive,
    clearPendingPfCancel: deps.clearPendingPfCancel,
    releaseFlightQueue: deps.releaseFlightQueue,
  });

  initHeroSection({
    tasksRef: { get: () => state.tasks },
    heroStatusEl: refs.heroStatusEl,
    getNextUpcomingTask: deps.getNextUpcomingTask,
  });

  initFlightPreview({
    isTauriRuntime: runtime.isTauriRuntime,
    showToast,
    unlockAudioIfNeeded,
    useSoundCheckbox: refs.useSoundCheckbox,
    validateCustomAudioPreview,
    persistFlightSettings,
    speedSelect: refs.speedSelect,
    heightSelect: refs.heightSelect,
    effectSelect: refs.effectSelect,
    planeSelect: refs.planeSelect,
    planeSizeSelect: refs.planeSizeSelect,
    particleSelect: refs.particleSelect,
    bubbleSelect: refs.bubbleSelect,
    bubblePositionSelect: refs.bubblePositionSelect,
    bubbleSizeSelect: refs.bubbleSizeSelect,
    bubbleBgColor: refs.bubbleBgColor,
    bubbleFontColor: refs.bubbleFontColor,
    soundSelect: refs.soundSelect,
    soundModeSelect: refs.soundModeSelect,
    useImageCheckbox: refs.useImageCheckbox,
    queueFlight,
    DEFAULT_FLIGHT_SETTINGS,
    customImageDataRef: { get: () => state.customImageData, set: (value) => { state.customImageData = value; } },
    customAudioNameRef: { get: () => state.customAudioName, set: (value) => { state.customAudioName = value; } },
    imagePreview: refs.imagePreview,
    clearImageBtn: refs.clearImageBtn,
    imageInput: refs.imageInput,
    updateTitleLogo: deps.updateTitleLogo,
    persistSetting,
    updateSoundMeta,
  });

  await initFlightListeners();

  initTauriListeners({
    listen,
    isTauriRuntime: runtime.isTauriRuntime,
    tasksRef: { get: () => state.tasks },
    stopLoopSoundLocal,
    clearAllSequences,
    clearFlightQueue,
    clearFlightStreak,
    pauseCountdown,
    stopCountdown,
    startCountdown,
    muteBtn: refs.muteBtn,
    invoke,
    showToast,
    createCountdownTask,
    triggerEmergencyLanding,
    setSkipPostFlight: deps.setSkipPostFlight,
    saveTasks,
    getCleanTasks: (tasks) => getCleanTasks(tasks ?? state.tasks),
    renderTaskView,
    autoCheckForUpdate,
    getCurrentWebviewWindow,
  });

  initMediaUpload({
    imageBtn: refs.imageBtn,
    imageInput: refs.imageInput,
    clearImageBtn: refs.clearImageBtn,
    imagePreview: refs.imagePreview,
    useImageCheckbox: refs.useImageCheckbox,
    customizeImageBtn: refs.customizeImageBtn,
    imageCollapse: refs.imageCollapse,
    editImageBtn: refs.editImageBtn,
    editImageInput: refs.editImageInput,
    editClearImageBtn: refs.editClearImageBtn,
    editImagePreview: refs.editImagePreview,
    editUseImageCheckbox: refs.editUseImageCheckbox,
    soundBtn: refs.soundBtn,
    soundInput: refs.soundInput,
    clearSoundBtn: refs.clearSoundBtn,
    useSoundCheckbox: refs.useSoundCheckbox,
    customizeSoundBtn: refs.customizeSoundBtn,
    soundCollapse: refs.soundCollapse,
    updateTitleLogo: deps.updateTitleLogo,
    setCustomImageData,
    persistSetting,
    showToast,
    buildCustomAudioObjectUrl,
    syncAudioObjectUrlTo,
    updateSoundMeta,
    setCustomAudioData,
    setCustomAudioObjectUrl,
    stopPreviewAudio,
    resetAudioPreview,
    revokeCustomAudioObjectUrl,
    unlockAudioIfNeeded,
    validateCustomAudioPreview,
    customImageDataRef: { get: () => state.customImageData, set: (value) => { state.customImageData = value; } },
    editImageDataRef: { get: () => state.editImageData, set: (value) => { state.editImageData = value; } },
    customAudioDataRef: { get: () => state.customAudioData, set: (value) => { state.customAudioData = value; } },
    customAudioNameRef: { get: () => state.customAudioName, set: (value) => { state.customAudioName = value; } },
  });

  initWindowEvents({
    saveTasks,
    getCleanTasks,
    tasks: state.tasks,
    set,
    speedSelect: refs.speedSelect,
    heightSelect: refs.heightSelect,
    effectSelect: refs.effectSelect,
    planeSelect: refs.planeSelect,
    planeSizeSelect: refs.planeSizeSelect,
    particleSelect: refs.particleSelect,
    bubbleSelect: refs.bubbleSelect,
    bubblePositionSelect: refs.bubblePositionSelect,
    bubbleSizeSelect: refs.bubbleSizeSelect,
    bubbleBgColor: refs.bubbleBgColor,
    bubbleFontColor: refs.bubbleFontColor,
    soundSelect: refs.soundSelect,
    soundModeSelect: refs.soundModeSelect,
    useSoundCheckbox: refs.useSoundCheckbox,
    useImageCheckbox: refs.useImageCheckbox,
    showToast,
    getCustomImageData: () => state.customImageData,
    getCustomAudioData: () => state.customAudioData,
    getCustomAudioName: () => state.customAudioName,
  });

  state.getTaskFilterState = initTaskFilter({ renderTaskView });

  initSettingsPanel({
    isTauriRuntime: runtime.isTauriRuntime,
    isMuted: state.isMuted,
    MUTED_ICON: refs.MUTED_ICON,
    UNMUTED_ICON: refs.UNMUTED_ICON,
    setMuted,
    syncMuteToTray,
    stopLoopSoundLocal,
    stopPreviewAudio,
    resetAudioPreview,
    set,
    syncThemeButtons,
    persistSetting,
    applyTheme,
    enableAutostart,
    disableAutostart,
    createMiniWindow,
    closeMiniWindow,
    positionMiniWindow,
    getMiniPositions,
    updateMiniPosGridActive,
    exportTasksAsJson,
    getCleanTasks,
    saveTasks,
    readBackupFromFile,
    hydrateTasks,
    setNextId,
    renderTaskView,
    checkForUpdate,
    openFeedbackPage,
    openReleasePage,
    getCurrentVersion,
    showToast,
    previewCustomSound,
    previewFlight,
    resetFlightSettings,
    invoke,
    unlockAudioIfNeeded,
    persistFlightSettings,
    speedSelect: refs.speedSelect,
    heightSelect: refs.heightSelect,
    effectSelect: refs.effectSelect,
    planeSelect: refs.planeSelect,
    planeSizeSelect: refs.planeSizeSelect,
    particleSelect: refs.particleSelect,
    bubbleSelect: refs.bubbleSelect,
    bubblePositionSelect: refs.bubblePositionSelect,
    bubbleSizeSelect: refs.bubbleSizeSelect,
    bubbleBgColor: refs.bubbleBgColor,
    bubbleFontColor: refs.bubbleFontColor,
    soundSelect: refs.soundSelect,
    soundModeSelect: refs.soundModeSelect,
    useSoundCheckbox: refs.useSoundCheckbox,
    useImageCheckbox: refs.useImageCheckbox,
    muteBtn: refs.muteBtn,
    tasksRef: { get: () => state.tasks, set: (value) => { state.tasks = value; } },
    isConfigOpenRef: { get: () => state.isConfigOpen, set: (value) => { state.isConfigOpen = value; } },
    isMutedRef: { get: () => state.isMuted, set: (value) => { state.isMuted = value; } },
    isStatsOpenRef: { get: () => state.isStatsOpen, set: (value) => { state.isStatsOpen = value; } },
  });

  initModalEvents({
    openNewModal,
    closeModal,
    openEditModal,
    selectColor,
    createCountdownTask: deps.createCountdownTask,
    createAlarmTask,
    getCleanTasks,
    saveTasks,
    renderTaskView,
    showToast,
    saveModalHandler,
    deleteTaskFn,
    isTauriRuntime: runtime.isTauriRuntime,
    tasksRef: { get: () => state.tasks },
    editingIdRef: { get: () => state.editingId, set: (value) => { state.editingId = value; } },
  });
}
