export const HOLIDAY_PRESETS = {
  // 法定假日 (solar)
  new_year: { label: '元旦', category: 'statutory', month: 1, day: 1, lunar: false },
  valentine: { label: '情人节', category: 'statutory', month: 2, day: 14, lunar: false },
  women_day: { label: '妇女节', category: 'statutory', month: 3, day: 8, lunar: false },
  qingming: { label: '清明节', category: 'statutory', month: 4, day: 5, lunar: false },
  labour_day: { label: '劳动节', category: 'statutory', month: 5, day: 1, lunar: false },
  youth_day: { label: '青年节', category: 'statutory', month: 5, day: 4, lunar: false },
  children_day: { label: '儿童节', category: 'statutory', month: 6, day: 1, lunar: false },
  party_day: { label: '建党节', category: 'statutory', month: 7, day: 1, lunar: false },
  army_day: { label: '建军节', category: 'statutory', month: 8, day: 1, lunar: false },
  teacher_day: { label: '教师节', category: 'statutory', month: 9, day: 10, lunar: false },
  national_day: { label: '国庆节', category: 'statutory', month: 10, day: 1, lunar: false },
  christmas: { label: '圣诞节', category: 'statutory', month: 12, day: 25, lunar: false },

  // 法定假日 (lunar)
  spring_festival: { label: '春节', category: 'statutory', month: 1, day: 1, lunar: true },
  lantern: { label: '元宵节', category: 'statutory', month: 1, day: 15, lunar: true },
  dragon_boat: { label: '端午节', category: 'statutory', month: 5, day: 5, lunar: true },
  mid_autumn: { label: '中秋节', category: 'statutory', month: 8, day: 15, lunar: true },
  double_ninth: { label: '重阳节', category: 'statutory', month: 9, day: 9, lunar: true },

  // 二十四节气 (solar, dates are approximate)
  lichun: { label: '立春', category: 'solar_term', month: 2, day: 4, lunar: false },
  yushui: { label: '雨水', category: 'solar_term', month: 2, day: 19, lunar: false },
  jingzhe: { label: '惊蛰', category: 'solar_term', month: 3, day: 6, lunar: false },
  chunfen: { label: '春分', category: 'solar_term', month: 3, day: 21, lunar: false },
  qingming_jieqi: { label: '清明', category: 'solar_term', month: 4, day: 5, lunar: false },
  guyu: { label: '谷雨', category: 'solar_term', month: 4, day: 20, lunar: false },
  lixia: { label: '立夏', category: 'solar_term', month: 5, day: 6, lunar: false },
  xiaoman: { label: '小满', category: 'solar_term', month: 5, day: 21, lunar: false },
  mangzhong: { label: '芒种', category: 'solar_term', month: 6, day: 6, lunar: false },
  xiazhi: { label: '夏至', category: 'solar_term', month: 6, day: 21, lunar: false },
  xiaoshu: { label: '小暑', category: 'solar_term', month: 7, day: 7, lunar: false },
  dashu: { label: '大暑', category: 'solar_term', month: 7, day: 23, lunar: false },
  liqiu: { label: '立秋', category: 'solar_term', month: 8, day: 7, lunar: false },
  chushu: { label: '处暑', category: 'solar_term', month: 8, day: 23, lunar: false },
  bailu: { label: '白露', category: 'solar_term', month: 9, day: 8, lunar: false },
  qiufen: { label: '秋分', category: 'solar_term', month: 9, day: 23, lunar: false },
  hanlu: { label: '寒露', category: 'solar_term', month: 10, day: 8, lunar: false },
  shuangjiang: { label: '霜降', category: 'solar_term', month: 10, day: 23, lunar: false },
  lidong: { label: '立冬', category: 'solar_term', month: 11, day: 7, lunar: false },
  xiaoxue: { label: '小雪', category: 'solar_term', month: 11, day: 22, lunar: false },
  daxue: { label: '大雪', category: 'solar_term', month: 12, day: 7, lunar: false },
  dongzhi: { label: '冬至', category: 'solar_term', month: 12, day: 22, lunar: false },
  xiaohan: { label: '小寒', category: 'solar_term', month: 1, day: 6, lunar: false },
  dahan: { label: '大寒', category: 'solar_term', month: 1, day: 20, lunar: false },
};
