export const HOLIDAY_PRESETS = {
  new_year: { label: '元旦', month: 1, day: 1 },
  valentine: { label: '情人节', month: 2, day: 14 },
  women_day: { label: '妇女节', month: 3, day: 8 },
  qingming: { label: '清明节', month: 4, day: 5 },
  labour_day: { label: '劳动节', month: 5, day: 1 },
  youth_day: { label: '青年节', month: 5, day: 4 },
  children_day: { label: '儿童节', month: 6, day: 1 },
  party_day: { label: '建党节', month: 7, day: 1 },
  army_day: { label: '建军节', month: 8, day: 1 },
  teacher_day: { label: '教师节', month: 9, day: 10 },
  national_day: { label: '国庆节', month: 10, day: 1 },
  christmas: { label: '圣诞节', month: 12, day: 25 },
  lichun: { label: '立春', month: 2, day: 4, approximate: true },
  yushui: { label: '雨水', month: 2, day: 19, approximate: true },
  jingzhe: { label: '惊蛰', month: 3, day: 6, approximate: true },
  chunfen: { label: '春分', month: 3, day: 21, approximate: true },
  qingming_jieqi: { label: '清明', month: 4, day: 5, approximate: true },
  guyu: { label: '谷雨', month: 4, day: 20, approximate: true },
  lixia: { label: '立夏', month: 5, day: 6, approximate: true },
  xiaoman: { label: '小满', month: 5, day: 21, approximate: true },
  mangzhong: { label: '芒种', month: 6, day: 6, approximate: true },
  xiazhi: { label: '夏至', month: 6, day: 21, approximate: true },
  xiaoshu: { label: '小暑', month: 7, day: 7, approximate: true },
  dashu: { label: '大暑', month: 7, day: 23, approximate: true },
  liqiu: { label: '立秋', month: 8, day: 7, approximate: true },
  chushu: { label: '处暑', month: 8, day: 23, approximate: true },
  bailu: { label: '白露', month: 9, day: 8, approximate: true },
  qiufen: { label: '秋分', month: 9, day: 23, approximate: true },
  hanlu: { label: '寒露', month: 10, day: 8, approximate: true },
  shuangjiang: { label: '霜降', month: 10, day: 23, approximate: true },
  lidong: { label: '立冬', month: 11, day: 7, approximate: true },
  xiaoxue: { label: '小雪', month: 11, day: 22, approximate: true },
  daxue: { label: '大雪', month: 12, day: 7, approximate: true },
  dongzhi: { label: '冬至', month: 12, day: 22, approximate: true },
  xiaohan: { label: '小寒', month: 1, day: 6, approximate: true },
  dahan: { label: '大寒', month: 1, day: 20, approximate: true },
};
